language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11

  allow_failures:
  - jdk: oraclejdk9
  - jdk: oraclejdk10
  - jdk: oraclejdk11

script: mvn clean install

after_success:
  - ./after-success.sh
