language: java

matrix:
  include:
  - jdk: oraclejdk8
  - jdk: openjdk8
  - jdk: oraclejdk9
  - jdk: openjdk9
  - jdk: oraclejdk10
  - jdk: openjdk10
  - jdk: oraclejdk11
  - jdk: openjdk11
  - jdk: oraclejdk12
  - jdk: openjdk12
  - jdk: oraclejdk13
  - jdk: openjdk13
  - jdk: oraclejdk14
  - jdk: openjdk14

  allow_failures:
  - jdk: oraclejdk8
  - jdk: oraclejdk9
  - jdk: oraclejdk10
  - jdk: oraclejdk11
  - jdk: oraclejdk12
  - jdk: oraclejdk13
  - jdk: oraclejdk14

script: mvn clean install

after_success:
  - ./after-success.sh
